--- # indicate begining of the play
#Run cmd: ansible-playbook --ask-become-pass install_apache.yml

# run this on all servers
- hosts: all
  become: true
  tasks:

# 1st play
  - name: install/update apache
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
