--- # indicate begining of the play
#Run cmd: ansible-playbook --ask-become-pass install_apache.yml

# run this on all servers
- hosts: all
  become: true
  tasks:

# 1st play
  - name: update repository index for Ubuntu and Debian
    apt: # module to run is apt
      update_cache: yes # update the server
    when: ansible_distribution in ["Ubuntu", "Debian"]

# 2nd play
  - name: install apache2 and php packages for Ubuntu and Debian
    apt: # module to run is apt
      name: 
        - apache2
        - libapache2-mod-php
      state: latest # latest tag
    when: ansible_distribution in ["Ubuntu", "Debian"]

# 3th play
  - name: update repository index for CentOS
    dnf: 
      update_cache: yes # update the server
    when: ansible_distribution == "CentOS"

# 4th play
  - name: install apache and php packages for CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
