--- # indicate begining of the play
#Run cmd: ansible-playbook --ask-become-pass install_apache.yml

# run this on all servers
- hosts: all
  become: true
  tasks:

# 1st play
  - name: install/update apache and php Ubuntu and Debian
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

# 2nd play
- name: install/update apache and php CentOS
    dnf:
      name:
        - httpd               
        - php 
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
