--- # indicate begining of the play
#Run cmd: ansible-playbook --ask-become-pass install_apache.yml

# run this on all servers
- hosts: all
  become: true
  tasks:

# 1st play
  - name: install/update apache2/php packages for Ubuntu/Debian
    apt: # module to run is apt
      name: 
        - apache2
        - libapache2-mod-php
      state: latest # latest tag
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

# 2th play
  - name: install/update apache and php packages for CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
